env:
  node: true
  mocha: true
extends: airbnb-base
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  no-console: off
  no-return-await: error
  require-await: error
