env:
  node: true
  mocha: true
extends: airbnb-base
rules:
  no-console: off
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never 
