language: node_js
node_js:
- '17'
before_install:
  - pyenv install 3.8.12
  - pyenv global 3.8.12 # for node-gyp
script: yarn spellcheck && yarn lint && yarn test
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: buriedunderbooks@hotmail.com
  on:
    tags: true
  api_key:
    secure: zTupwYlXidoDMG7x4atDkwDjU7qPWex1/NYxelTU45U9bB6Ul2CnKgLgCb55qEG58MN8oHHiJ6bbo0qVYEM2SXJfuJYpmJicLC9fU9OwU7kaXLVAAijJpIHvLavhU7Nlco/aTDKpj/Kszw8CrB1P3rrXiuIGtntXwQih6or0681R7r0SJ0KO02k15eSnmK1ae//ljCFjIBO5RBfbvntHXR8H+aQBldICN7ufc8hjIe7NR3TVa4ffyQNWXVs3ZeWjPKYYCxIbKZ55gotFXIwD8XU2WEOqJcL5EubRBFo0dPLdunkQzYAsMLJbZndnktrkvUMSrQ/FgC1gXhp49ODFZcyM3wnU3iH4zDWu7GLf9o2I32n3XNxphFDbUlVTLZfrVEcBqwGD3Ojw5bFCruQTdF987RrEBkYllo7QO1DioJmq8HU2EuFNQEzE/C4y898xU5n1gIoyjyFQgsg9AcBzxR6n6rvUS+NFhxcZNRRIAvy+2Xr93ZvfljNAPkkg62dBeX4Kc4CvnZFoh3AI2lJzxhhkN0zzEzpHKnSlJp9ZXa3pC1Y5/0nB36szuAUk9WFG8mokwWjxZLYrdUJE90Vtm4JzNQjr6A8MJrQbnh+ILlJTzmfcckaEsnaSqabpETLQnpwYEuSb34zi8WuHGF2DZxfHa1S5hqIbHY8EJF1ARQU=
